# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LicenceKey.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from HelperClass import LoadingGif
from PyQt5.QtCore import Qt, QTimer
from PyQt5 import QtWidgets
from PosTerminal import Ui_PosWindow
import sys

class Ui_LicenceWindow(object):

    def setupUi(self, LicenceWindow):
        LicenceWindow.setObjectName("LicenceWindow")
        LicenceWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LicenceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.lineEdit_licenceField = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_licenceField.setObjectName("lineEdit_licenceField")
        self.verticalLayout_3.addWidget(self.lineEdit_licenceField)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_activate = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_activate.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_activate.setObjectName("pushButton_activate")

        """Button Event Start"""
        # TODO::Button Event LicenceKey

        self.pushButton_activate.clicked.connect(self.button_clicked)

        """Button Event End"""

        self.horizontalLayout.addWidget(self.pushButton_activate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        LicenceWindow.setCentralWidget(self.centralwidget)
        self.actionOrderList = QtWidgets.QAction(LicenceWindow)
        self.actionOrderList.setObjectName("actionOrderList")
        self.actionCustomer_Import_licence = QtWidgets.QAction(LicenceWindow)
        self.actionCustomer_Import_licence.setObjectName("actionCustomer_Import_licence")
        self.actionProduct_Import_licence = QtWidgets.QAction(LicenceWindow)
        self.actionProduct_Import_licence.setObjectName("actionProduct_Import_licence")
        self.actionPOS_Terminal_licence = QtWidgets.QAction(LicenceWindow)
        self.actionPOS_Terminal_licence.setObjectName("actionPOS_Terminal_licence")

        self.retranslateUi(LicenceWindow)
        QtCore.QMetaObject.connectSlotsByName(LicenceWindow)

    def retranslateUi(self, LicenceWindow):
        _translate = QtCore.QCoreApplication.translate
        LicenceWindow.setWindowTitle(_translate("LicenceWindow", "LicenceKey"))
        self.label.setText(_translate("LicenceWindow", "Perfect POS"))
        self.label_2.setText(_translate("LicenceWindow", "Enter Licence Key"))
        self.pushButton_activate.setText(_translate("LicenceWindow", "Activate"))
        self.label_3.setText(_translate("LicenceWindow", "© Bit Byte Technology"))
        self.actionOrderList.setText(_translate("LicenceWindow", "OrderList"))
        self.actionCustomer_Import_licence.setText(_translate("LicenceWindow", "Customer Import"))
        self.actionProduct_Import_licence.setText(_translate("LicenceWindow", "Product Import"))
        self.actionPOS_Terminal_licence.setText(_translate("LicenceWindow", "POS Terminal"))

    def button_clicked(self):
        print("dadad")
        self.w = LoadingGif()
        self.w.show()
        timer = QTimer()
        timer.singleShot(3000, self.nextWork)

    def nextWork(self):
        print("Printed after 4 secs")
        self.w.stopAnimation()
        self.w.pop_up("Congratulations! Licence Activated")
        self.openWindow()

    def openWindow(self):
        print("here")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PosWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        # ui = LicenceWindow
        # ui.hide()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LicenceWindow = QtWidgets.QMainWindow()
    ui = Ui_LicenceWindow()
    ui.setupUi(LicenceWindow)
    LicenceWindow.show()
    sys.exit(app.exec_())
